version: '3.9'
services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log:/var/log/nginx
    depends_on:
      php:
        condition: service_started
  php:
    build:
      context: ./docker
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mariadb-admin" , "-u", "root", '-proot', "ping", "-h", "localhost"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./support/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql
  print-status:
    image: busybox
    command: "echo '---\nSERVER RUNNING AT http://localhost:8000. USE CTRL+C TO TERMINATE.\n---'"    
    depends_on:
      web:
        condition: service_started
      mariadb:
        condition: service_healthy
volumes:
    db_data:
